version: '2'

services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    ports:
      - 9042:9042
      - 7000:7000
    expose:
      - 9042
##конфиги для cassandra.yml
    environment:
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_CLUSTER_NAME='cassandra-cluster'
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_LISTEN_ADRESS=192.168.1.200
      - CASSANDRA_START_PRC=true
      - CASSANDRA_BROADCAST_ADDRESS=192.168.1.200
    command: bash -c 'if [ -z "$$(ls -A /var/lib/cassandra/)" ] ; then sleep 0; fi && /usr/local/bin/docker-entrypoint.sh cassandra -f'
    networks:
      CASnet:
        ipv4_address: 192.168.1.200

  cassandra2:
    image: cassandra:latest
    restart: always
    container_name: cassandra2
    ports:
      - 7001:7000
      - 9043:9042
    environment:
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_CLUSTER_NAME='cassandra-cluster'
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_LISTEN_ADRESS=192.168.1.201
      - CASSANDRA_START_PRC=true
      - CASSANDRA_BROADCAST_ADDRESS=192.168.1.201
    command: bash -c 'if [ -z "$$(ls -A /var/lib/cassandra/)" ] ; then sleep 60; fi && /usr/local/bin/docker-entrypoint.sh cassandra -f'
    networks:
      CASnet:
        ipv4_address: 192.168.1.201

  cassandra3:
    image: cassandra:latest
    restart: always
    container_name: cassandra3
    ports:
      - 9044:9042
      - 7002:7000
    environment:
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_CLUSTER_NAME='cassandra-cluster'
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_LISTEN_ADRESS=192.168.1.202
      - CASSANDRA_START_PRC=true
      - CASSANDRA_BROADCAST_ADDRESS=192.168.1.202
    command: bash -c 'if [ -z "$$(ls -A /var/lib/cassandra/)" ] ; then sleep 120; fi && /usr/local/bin/docker-entrypoint.sh cassandra -f'
    networks:
      CASnet:
        ipv4_address: 192.168.1.202

networks:
  CASnet:
      name: CASnet
      driver: macvlan
      driver_opts:
        parent: enp0s8
      ipam:
        config:
          - subnet: "192.168.1.0/24"
            gateway: "192.168.1.199"
            ip_range: "192.168.1.200/30"
